# Build settings
markdown: redcarpet
highlighter: pygments

# Site settings
title: "Alex Kramer"
description: > # this means to ignore newlines until "email:"
   Ruminations of a soccer playing software engineer

email: ackramer19@gmail.com
#blog logo
logo: "/assets/images/df_logo.jpg"
# blog cover
cover: "/assets/images/01669_cole_field.jpg"

name: 'Alex Kramer'
author: 'Alex Kramer'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://www.alexckramer.com" # the base hostname & protocol for your site
baseurl: ""

gems:
  - jekyll-sitemap

exclude: [vendor]

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/alexckramer
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

  - icon:	github
    url:	https://github.com/alexkramer
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

  - icon:	google-plus
    url:	https://google.com/+AlexKramer19
    desc:	Add me on google+
    share_url:
    share_title:
    share_link:

  - icon: linkedin
    url:  https://www.linkedin.com/in/alexckramer
    desc: Connect on linkedIn
    share_url:
    share_title:
    share_link:
